# Generated by Django 2.1.2 on 2018-11-26 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181126_1900'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bear',
            new_name='Perro',
        ),
    ]
