# Generated by Django 2.1.2 on 2018-12-12 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20181126_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('costop', models.CharField(max_length=255)),
                ('costor', models.CharField(max_length=255)),
                ('tienda', models.CharField(max_length=255)),
                ('notas', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Perro',
        ),
    ]
