# Generated by Django 2.1.2 on 2018-12-12 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20181212_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='idlist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.Lista'),
            preserve_default=False,
        ),
    ]
