# Generated by Django 2.1.2 on 2018-12-12 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_producto_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='idlist',
        ),
    ]
